# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'SportStory' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 3.0'
  pod 'Masonry','~> 1.0.2'
  
  # 融云
  pod 'RongCloudIM/IMLib', '~> 2.8.3'
  pod 'RongCloudIM/IMKit', '~> 2.8.3'
  # Pods for SportStory

  target 'SportStoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SportStoryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
